apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: simple-deployment
  namespace: labs  
spec:  
  replicas: 3  
  selector:
    matchLabels:
      app: my-app 
  template:  
    metadata:  
      labels:  
        app: my-app 
    spec:  
      containers:  
        - name: my-app-container  
          image: kodekloud/webapp-delayed-start 
          ports:  
            - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /live
          port: 8080
        periodSeconds: 3
        initialDelaySeconds: 130 
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080 
