apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: labs
spec:
  containers:
    - name: development-webapp
      image: kodekloud/webapp-delayed-start
      resources:
        requests:
          cpu: "250m"          
          memory: "512Mi"      
        limits:
          cpu: "500m"          
          memory: "1Gi"       
